import ROOT
import sys

ROOT.gSystem.Load('libMitAnaDataTree.so')
ROOT.gSystem.Load('libMitPhysicsMods.so')
ROOT.gSystem.Load('libMitTagAndProbeMods.so')

#from MitAna.TreeMod.bambu import mithep, analysis
mithep = ROOT.mithep
analysis = mithep.Analysis()
analysis.SetOutputName('ntuples.root')
catalog = mithep.Catalog('/home/cmsprod/catalog')
#dataset = catalog.FindDataset('t2mit/filefi/032', 'r12a-smu-j22-v1', '0000', 1)
dataset = catalog.FindDataset('t2mit/filefi/041', 'SingleMuon+Run2015B-PromptReco-v1+AOD', '0000', 1)
analysis.AddDataset(dataset)
analysis.SetProcessNEvents(10000)

hltMod = mithep.HLTMod()
hltMod.SetBitsName('HLTBits')
hltMod.SetTrigObjsName('SingleMuonTriggerObjects')
triggerList = open('muon_triggers_2012.txt')
for line in triggerList:
    hltMod.AddTrigger(line.strip())
#hltMod.AddTrigger('HLT_IsoMu24_v*')
#hltMod.AddTrigger('HLT_IsoMu24_eta2p1_v*')
#hltMod.AddTrigger('HLT_IsoMu17_eta2p1_v*')
# 2015 triggers:
#hltMod.AddTrigger('HLT_DoubleMu33NoFiltersNoVtx_v*')
#hltMod.AddTrigger('HLT_DoubleMu38NoFiltersNoVtx_v*')
#hltMod.AddTrigger('HLT_DoubleMu23NoFiltersNoVtxDisplaced_v*')
#hltMod.AddTrigger('HLT_DoubleMu28NoFiltersNoVtxDisplaced_v*')
#hltMod.AddTrigger('HLT_DoubleMu4_LowMassNonResonantTrk_Displaced_v*')
#hltMod.AddTrigger('HLT_DoubleMu4_PsiPrimeTrk_Displaced_v*')
#hltMod.AddTrigger('HLT_Mu16_eta2p1_CaloMET30_v*')
#hltMod.AddTrigger('HLT_IsoMu16_eta2p1_CaloMET30_v*')
#hltMod.AddTrigger('HLT_IsoMu17_eta2p1_v*')
#hltMod.AddTrigger('HLT_DoubleIsoMu17_eta2p1_v*')
#hltMod.AddTrigger('HLT_IsoMu20_v*')
#hltMod.AddTrigger('HLT_IsoMu20_eta2p1_v*')
#hltMod.AddTrigger('HLT_IsoMu24_eta2p1_v*')
#hltMod.AddTrigger('HLT_IsoMu27_v*')
#hltMod.AddTrigger('HLT_IsoTkMu20_v*')
#hltMod.AddTrigger('HLT_IsoTkMu20_eta2p1_v*')
#hltMod.AddTrigger('HLT_IsoTkMu24_eta2p1_v*')
#hltMod.AddTrigger('HLT_IsoTkMu27_v*')
#hltMod.AddTrigger('HLT_L2Mu10_v*')
#hltMod.AddTrigger('HLT_L2DoubleMu23_NoVertex_v*')
#hltMod.AddTrigger('HLT_Mu17_Mu8_v*')
#hltMod.AddTrigger('HLT_Mu17_Mu8_DZ_v*')
#hltMod.AddTrigger('HLT_Mu17_Mu8_SameSign_DZ_v*')
#hltMod.AddTrigger('HLT_Mu20_Mu10_v*')
#hltMod.AddTrigger('HLT_Mu20_Mu10_DZ_v*')
#hltMod.AddTrigger('HLT_Mu20_Mu10_SameSign_DZ_v*')
#hltMod.AddTrigger('HLT_Mu17_TkMu8_DZ_v*')
#hltMod.AddTrigger('HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_v*')
#hltMod.AddTrigger('HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_v*')
#hltMod.AddTrigger('HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v*')
#hltMod.AddTrigger('HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v*')
#hltMod.AddTrigger('HLT_Mu25_TkMu0_dEta18_Onia_v*')
#hltMod.AddTrigger('HLT_Mu27_TkMu8_v*')
#hltMod.AddTrigger('HLT_Mu30_TkMu11_v*')
#hltMod.AddTrigger('HLT_Mu40_TkMu11_v*')
#hltMod.AddTrigger('HLT_Mu20_v*')
#hltMod.AddTrigger('HLT_TkMu20_v*')
#hltMod.AddTrigger('HLT_Mu24_eta2p1_v*')
#hltMod.AddTrigger('HLT_TkMu24_eta2p1_v*')
#hltMod.AddTrigger('HLT_Mu27_v*')
#hltMod.AddTrigger('HLT_TkMu27_v*')
#hltMod.AddTrigger('HLT_Mu50_v*')
#hltMod.AddTrigger('HLT_Mu55_v*')
#hltMod.AddTrigger('HLT_Mu45_eta2p1_v*')
#hltMod.AddTrigger('HLT_Mu50_eta2p1_v*')
#hltMod.AddTrigger('HLT_DoubleMu18NoFiltersNoVtx_v*')
#hltMod.AddTrigger('HLT_PFMET120_NoiseCleaned_Mu5_v*')
#hltMod.AddTrigger('HLT_Mu8_TrkIsoVVL_v*')
#hltMod.AddTrigger('HLT_Mu17_TrkIsoVVL_v*')
#hltMod.AddTrigger('HLT_Mu24_TrkIsoVVL_v*')
#hltMod.AddTrigger('HLT_Mu34_TrkIsoVVL_v*')
#hltMod.AddTrigger('HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v*')
#hltMod.AddTrigger('HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_v*')
#hltMod.AddTrigger('HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v*')
#hltMod.AddTrigger('HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v*')
#hltMod.AddTrigger('HLT_Mu30_Ele30_CaloIdL_GsfTrkIdVL_v*')
#hltMod.AddTrigger('HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v*')
#hltMod.AddTrigger('HLT_Mu12_Photon25_CaloIdL_v*')
#hltMod.AddTrigger('HLT_DiMu9_Ele9_CaloIdL_TrackIdL_v*')
#hltMod.AddTrigger('HLT_Mu3er_PFHT140_PFMET125_NoiseCleaned_v*')
#hltMod.AddTrigger('HLT_Dimuon0_Jpsi_Muon_v*')
#hltMod.AddTrigger('HLT_Dimuon0_Upsilon_Muon_v*')
#hltMod.AddTrigger('HLT_TrkMu15_DoubleTrkMu5NoFiltersNoVtx_v*')
#hltMod.AddTrigger('HLT_TrkMu17_DoubleTrkMu8NoFiltersNoVtx_v*')
#hltMod.AddTrigger('HLT_Mu8_v*')
#hltMod.AddTrigger('HLT_Mu17_v*')
#hltMod.AddTrigger('HLT_Mu24_v*')
#hltMod.AddTrigger('HLT_Mu34_v*')
#hltMod.AddTrigger('HLT_Mu300_v*')
#hltMod.AddTrigger('HLT_Mu350_v*')

goodPVMod = mithep.GoodPVFilterMod()
goodPVMod.SetMinVertexNTracks(0)
goodPVMod.SetMinNDof(4)
goodPVMod.SetMaxAbsZ(24.0)
goodPVMod.SetMaxRho(2.0)
goodPVMod.SetIsMC(False)
goodPVMod.SetVertexesName('PrimaryVertexes')

pfPUMod = mithep.SeparatePileUpMod()
pfPUMod.SetPFNoPileUpName('pfNoPU')
pfPUMod.SetPFPileUpName('pfPU')

BitwiseMuonNtuplesMod = mithep.BitwiseMuonNtuples('BitwiseMuonNtuples', 'Flat ntuples producer')

#analysis.setSequence(hltMod * goodPVMod * tagMuonIdMod * probeMuonIdMod * ntuplesMod)
analysis.AddSuperModule(hltMod)
hltMod.Add(goodPVMod)
goodPVMod.Add(pfPUMod)
pfPUMod.Add(BitwiseMuonNtuplesMod)

analysis.Run(False)
