import ROOT
import sys

ROOT.gSystem.Load('libMitAnaDataTree.so')
ROOT.gSystem.Load('libMitPhysicsMods.so')
ROOT.gSystem.Load('libMitTagAndProbeMods.so')

mithep = ROOT.mithep
analysis = mithep.Analysis()
analysis.SetOutputName('electronNtuples.root')
catalog = mithep.Catalog('/home/cmsprod/catalog')
dataset = catalog.FindDataset('t2mit/filefi/041', 'SingleElectron+Run2015B-PromptReco-v1+AOD', '0000', 1)
analysis.AddDataset(dataset)
analysis.SetProcessNEvents(10000)

hltMod = mithep.HLTMod()
hltMod.SetBitsName('HLTBits')
hltMod.SetTrigObjsName('SingleElectronTriggerObjects')
# 2015 triggers:
hltMod.AddTrigger('HLT_DoubleEle24_22_eta2p1_WPLoose_Gsf_v*')
hltMod.AddTrigger('HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW_v*')
hltMod.AddTrigger('HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_v*')
hltMod.AddTrigger('HLT_Ele25WP60_Ele8_Mass55_v*')
hltMod.AddTrigger('HLT_Ele25WP60_SC4_Mass55_v*')
hltMod.AddTrigger('HLT_Ele22_eta2p1_WPLoose_Gsf_v*')
hltMod.AddTrigger('HLT_Ele22_eta2p1_WPTight_Gsf_v*')
hltMod.AddTrigger('HLT_Ele23_WPLoose_Gsf_v*')
hltMod.AddTrigger('HLT_Ele27_eta2p1_WPLoose_Gsf_v*')
hltMod.AddTrigger('HLT_Ele27_eta2p1_WPTight_Gsf_v*')
hltMod.AddTrigger('HLT_Ele32_eta2p1_WPLoose_Gsf_v*')
hltMod.AddTrigger('HLT_Ele32_eta2p1_WPTight_Gsf_v*')
hltMod.AddTrigger('HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v*')
hltMod.AddTrigger('HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v*')
hltMod.AddTrigger('HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_v*')
hltMod.AddTrigger('HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_v*')
hltMod.AddTrigger('HLT_Ele17_CaloIdL_TrackIdL_IsoVL_v*')
hltMod.AddTrigger('HLT_Ele23_CaloIdL_TrackIdL_IsoVL_v*')
hltMod.AddTrigger('HLT_Ele12_CaloIdL_TrackIdL_IsoVL_v*')
hltMod.AddTrigger('HLT_Ele27_eta2p1_WPLoose_Gsf_HT200_v*')
hltMod.AddTrigger('HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300_v*')
hltMod.AddTrigger('HLT_Ele15_IsoVVVL_PFHT350_PFMET70_v*')
hltMod.AddTrigger('HLT_Ele15_IsoVVVL_PFHT600_v*')
hltMod.AddTrigger('HLT_Ele15_PFHT300_v*')

goodPVMod = mithep.GoodPVFilterMod()
goodPVMod.SetMinVertexNTracks(0)
goodPVMod.SetMinNDof(4)
goodPVMod.SetMaxAbsZ(24.0)
goodPVMod.SetMaxRho(2.0)
goodPVMod.SetIsMC(False)
goodPVMod.SetVertexesName('PrimaryVertexes')

pfPUMod = mithep.SeparatePileUpMod()
pfPUMod.SetPFNoPileUpName('pfNoPU')
pfPUMod.SetPFPileUpName('pfPU')

tagElectronIdMod = mithep.ElectronIdMod()
tagElectronIdMod.SetPtMin(25.)
tagElectronIdMod.SetEtaMax(2.4)
tagElectronIdMod.SetIdType(mithep.ElectronTools.kTight)
tagElectronIdMod.SetIsoType(mithep.ElectronTools.kNoIso)
tagElectronIdMod.SetApplyD0Cut(True)
tagElectronIdMod.SetApplyDZCut(True)
tagElectronIdMod.SetWhichVertex(0)
tagElectronIdMod.SetInputName('Electrons')
tagElectronIdMod.SetOutputName('TightElectrons')
tagElectronIdMod.SetPFNoPileupCandidatesName('pfNoPU')
tagElectronIdMod.SetPFPileupCandidatesName('pfPU')

probeElectronIdMod = mithep.ElectronIdMod()
probeElectronIdMod.SetPtMin(25.)
probeElectronIdMod.SetEtaMax(2.4)
probeElectronIdMod.SetIdType(mithep.ElectronTools.kLoose)
probeElectronIdMod.SetIsoType(mithep.ElectronTools.kNoIso)
probeElectronIdMod.SetApplyD0Cut(False)
probeElectronIdMod.SetApplyDZCut(False)
probeElectronIdMod.SetOutputName('LooseElectrons')
probeElectronIdMod.SetPFNoPileupCandidatesName('pfNoPU')
probeElectronIdMod.SetPFPileupCandidatesName('pfPU')

ntuplesMod = mithep.ElectronNtuples('ElectronNtuples', 'Flat ntuples producer')
ntuplesMod.SetTagElectronsName('TightElectrons')
ntuplesMod.SetProbeElectronsName('LooseElectrons')
ntuplesMod.SetTriggerObjectsName('SingleElectronTriggerObjects')

analysis.AddSuperModule(hltMod)
hltMod.Add(goodPVMod)
goodPVMod.Add(pfPUMod)
pfPUMod.add(tagElectronIdMod)
tagElectronIdMod.Add(probeElectronIdMod)
probeElectronIdMod.Add(ntuplesMod)

analysis.Run(False)
